app_config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('weather.urls', namespace='weather')),
    path('user/', include('users.urls', namespace='user')),
]

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.apps import UsersConfig
from users.views import UserRegisterView

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', UserRegisterView.as_view(), name='register'),
]

weather/urls.py
from django.urls import path

from weather.apps import WeatherConfig
from weather.views import get_weather, CityDetailView

app_name = WeatherConfig.name

urlpatterns = [
    path('', get_weather, name='index'),
    path('detail/<int:pk>/', CityDetailView.as_view(), name='detail'),
]

weather/models.py
from django.contrib.auth.models import User
from django.db import models


class City(models.Model):
    city = models.CharField(max_length=255, verbose_name='City')
    latitude = models.FloatField(verbose_name='Latitude')
    longitude = models.FloatField(verbose_name='Longitude')

    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='user')

    def __str__(self):
        return f'{str(self.city)}(lat={self.latitude}, lon={self.longitude})'

    class Meta:
        verbose_name = 'City'
        verbose_name_plural = 'Cites'

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserRegistrationForm(UserCreationForm):
    """Класс формы для отображения полей при регистрации пользователя"""
    class Meta:
        model = User
        fields = ('username', 'password1', 'password2',)

users/views.py
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views.generic import CreateView

from users.forms import UserRegistrationForm


class UserRegisterView(CreateView):
    model = User
    template_name = 'users/registration.html'
    form_class = UserRegistrationForm
    success_url = reverse_lazy('user:login')

weather/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render
from django.views.generic import DetailView

from weather.models import City
from weather.services import get_weather_with_site, get_coordinates


@login_required(login_url='user/')
def get_weather(request):
    if request.method == 'POST':
        city = request.POST.get('city')
        city_coordinates = get_coordinates(city)
        if city_coordinates is None:
            context_data = {'message': f"Город {city} не найден"}
            return render(request, 'weather/weather_result.html', context_data)
        print(request.user)
        City.objects.create(city=city.capitalize(),
                            latitude=city_coordinates['latitude'],
                            longitude=city_coordinates['longitude'],
                            user=request.user)
        context_data = get_weather_with_site(city_coordinates)
        context_data['city'] = city.capitalize()
        return render(request, 'weather/weather_result.html', context_data)

    context_data = {'object_list': City.objects.filter(user=request.user).distinct('city')}
    return render(request, 'weather/input_city_form.html', context_data)


class CityDetailView(DetailView):
    model = City
    template_name = 'weather/weather_detail.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        coordinates = {'latitude': self.object.latitude,
                       'longitude': self.object.longitude}
        context_data['object'] = get_weather_with_site(coordinates)
        return context_data

users/templates/users/login.html
{% extends 'weather/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Вход</button>
                        <a class="btn btn-outline-success" href="{% url 'user:register' %}">Регистрация</a>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/registration.html
{% extends 'weather/base.html' %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col-6">
            <div class="card">
                <div class="card-header"></div>
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-success">Регистрация</button>
                    </form>
                </div>
                <div class="card-footer"></div>
            </div>
        </div>
    </div>

{% endblock %}

weather/templates/weather/base.html
{% load static %}

<!doctype html>
<html lang="ru" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Пример на bootstrap 5: Форма входа - макет и дизайн формы · Версия v5.3.1">
    <title>Форма входа | Signin Template for Bootstrap · Версия v5.3.1</title>

    {#    <link rel="canonical" href="https://bootstrap-4.ru/docs/5.3/examples/sign-in/">#}

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.3/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#712cf9">


<style>
    .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
    }

    @media (min-width: 768px) {
        .bd-placeholder-img-lg {
            font-size: 3.5rem;
        }
    }

    .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
    }

    .bi {
        vertical-align: -.125em;
        fill: currentColor;
    }

    .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
    }

    .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
    }

    .bd-mode-toggle {
        z-index: 1500;
    }
</style>



<main class="form-signin w-100 m-auto">
    {% if user.is_authenticated %}
        <form action="{% url 'user:logout' %}" method="post">
            {% csrf_token %}
            <button type="submit" class="btn-bd-primary">Logout</button>
        </form>
    {% endif %}
    {% block content %}

    {% endblock %}

</main>

<script src="{% static 'js/bootstrap.bundle.min.js' %}" crossorigin="anonymous"></script>


</body>
</html>

weather/templates/weather/input_city_form.html
{% extends 'weather/base.html' %}

{% block content %}
    <div class="row">
        <form method="post">
            {% csrf_token %}
            <h1 class="h3 mb-3 fw-normal">Введите название города</h1>

            <div class="form-floating col-6 text-center">
                <input type="text" class="form-control" id="floatingInput" placeholder="Город" name="city">
                <label for="floatingInput">Город</label>
            </div>

            <div class="col-6 mt-2">
                <button class="btn btn-primary w-100 py-2" type="submit">Отправить</button>
            </div>

        </form>
    </div>
    <div class="row m-lg-2">
    <h3>История запросов</h3>
        <table class="table">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Город</th>
                <th scope="col">Широта</th>
                <th scope="col">Долгота</th>
            </tr>
            </thead>
            <tbody>
            {% for object in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{% url 'weather:detail' object.pk %}">{{ object.city }}</a></td>
                <td>{{ object.latitude }}</td>
                <td>{{ object.longitude }}</td>
            </tr>
            {% endfor %}
            </tbody>
        </table>

    </div>
{% endblock %}

weather/templates/weather/weather_detail.html
{% extends 'weather/base.html' %}

{% block content %}
    <h1>Прогноз погоды на ближайшие 2 часа</h1>
    <table class="table">
        <thead>
        <tr>
            <th scope="col">Город</th>
            <th scope="col">Температура</th>
            <th scope="col">Осадки</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>{{ city }}</td>
            <td>{{ object.first_hour }} - {{ object.second_hour }}</td>
            {% if object.rain1 <= 0.2 and object.rain2 <= 0.2 %}
                <td>Осадки не ожидаются</td>
            {% else %}
                <td>Возможны осадки</td>
            {% endif %}
        </tr>
        </tbody>
    </table>
    <div>
        <a class="btn btn-outline-warning" href="{% url 'weather:index' %}">На гланую</a>
    </div>
{% endblock %}

weather/templates/weather/weather_result.html
{% extends 'weather/base.html' %}
{% load static %}

{% block content %}
    {% if not first_hour %}
        <h1>{{ message }}</h1>
        <a href="{% url 'weather:index' %}" class="btn btn-success">Вернуться к поиску города</a>
    {% else %}
        <h1>Погода в городе {{ city }} на ближайшие 2 часа</h1>
        <h2>Ожидаемая температура : {{ first_hour }} - {{ second_hour }}</h2>
        {% if rain1 <= 0.2 and rain2 <= 0.2 %}
            <h2>Осадки: Осадков не ожидается</h2>
        {% else %}
            <h2>Осадки: Возможны осадки</h2>
        {% endif %}
    {% endif %}
{% endblock %}